version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 2350:80
        volumes:
            - ./app:/var/www/html

    db:
        image: mariadb
        restart: always
        environment:
            MY_SQL_DATABASE: tpfetch_react
            MYSQL_ROOT_PASSWORD: example

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
